### ISSUE TITLE
Prepare submission material

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-centrifuge#13]
Submission checklist

- [x] 2 Icons (for Ledger device and Ledger Manager)
- [x] Companion app (binaries or package, for Windows/MacOS/Linux)
- [x] Contact information 
- [x] Link to tutorial hosted on third party website
- [x] Video of your application running on the Ledger device

Details in: https://docs.google.com/document/d/1Rgn_myiYeftg9zUAfb5veJuPBoHH0eq3HS4YGyGCc5k/edit?usp=sharing

**Comment by StreamOfMaya** [comment]
Ledger app was submitted on 20 April 2021
