### ISSUE TITLE
Centrifuge parachain migration renders app inoperable

### ISSUE THREAD

**Issue by wickles** [Zondax/ledger-centrifuge#35]
The Centrifuge app for Ledger is no longer operational. 

Centrifuge has migrated to a parachain on the Polkadot relay chain. All Ledger accounts are now inaccessible because the app only supports the old frozen chain and not the currently functioning parachain.

**Comment by carlosala** [comment]
Hi! There's a new release (`v1.1005.0`) that support Centrifuge parachain balances pallet. As LNX doesn't support unofficial app sideloading (aka you can only install apps in Ledger Live) this app version is, for the moment, only available for NanoS and NanoSP using our installers, found in the latest release.
Thanks for your report, I hope that this is going to help you use the new Centrifuge chain with your ledger device.

**Comment by wickles** [comment]
Well, why isn't it available on Ledger Live yet?

**Comment by carlosala** [comment]
We don't control Ledger releases of apps, they have tons of upgrades to review and it's a slow process.

**Comment by wickles** [comment]
I am testing this now on a Nano S Plus. I have the loaded the latest Centrifuge app v1.1005.0 and it does not work. 

When I try to add my account on Polkadot.js with webUSB or webHID:

> Data is invalid.

When I try to use my existing attached account with Polkadot.js extension, I get a transaction popup with the error:

> There is no known Ledger app available for this chain

When I try to attach an account to Polkadot.js extension:

> Ledger error: Data is invalid

Would love to hear your thoughts on this.

**Comment by wickles** [comment]
Reminder: It has been *three months* since the parachain launched with no warning to Ledger users on Centrifuge.

**Comment by carlosala** [comment]
Hi @wickles,
You have a new version solving that issue, thanks for your report.
