### ISSUE TITLE
ledger-centrifuge cannot transfer out the CFG token

### ISSUE THREAD

**Issue by lzxeth** [Zondax/ledger-centrifuge#49]
hi, 
according to the official documentation of ledger, i imported ledger-centrifuge to my talisman wallet , everything is going smooth, then, I sent the CFG token to the ledger-centrifuge, ledger-centrifuge wallet balance can also be displayed normally, but I can't transfer it out from the ledger-centrifuge.

When transferring tokens from ledger-centrifuge, the "Approve on Ledger" button pops up, and an error is reported after clicking: _this type of transaction is not supported on your ledger. you should check for firmware updates in ledger live before trying again._

please help me to solve this problem.

**related information is as follows:**
ledger doc : https://support.ledger.com/hc/en-us/articles/11158925739677-Centrifuge-CFG-?support=true

app version:
talisman : 1.17.5    
ledger live : 2.62.2  
ledger centirfuge : 1.10070.1  
ledger firmware version : 2.2.1

hey are all up to date, and it doesn't seem to be an issue with the version.

:link: [zboto Link](https://app.clickup.com/t/861n2ta86)

**Comment by JuanaZondax** [comment]
Hi @lzxeth! I apologize for the inconvenience you're facing. Unfortunately, the Centrifuge app is no longer maintained by our team, and it appears to be broken. We recommend reaching out to the Centrifuge team for assistance or exploring alternative solutions
